version: "3.9"

services:

  db:
    image: postgres:16.1
    volumes:
      - storage:/var/lib/postgresql/data/
    restart: always
    env_file:
      - .env
    ports:
    - "5432:5432"

volumes:
  storage: